// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
