// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {monitor} from '../models';

export function GetSessions():Promise<Array<monitor.Session>>;

export function ToggleWindow():Promise<void>;
