// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {monitor} from '../models';
import {main} from '../models';

export function GetHistory():Promise<Array<monitor.ProjectHistory>>;

export function GetSessions():Promise<Array<monitor.Session>>;

export function GetSettings():Promise<main.Settings>;

export function HideWindow():Promise<void>;

export function OpenSession(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ResumeSession(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleWindow():Promise<void>;

export function UpdateSettings(arg1:main.Settings):Promise<void>;
